name = "gastronomos"
main = "src/frontend-worker-simple.ts"
compatibility_date = "2024-01-01"

[site]
bucket = "./gastronomos-frontend/out"

[env.production]
name = "gastronomos"
vars = { ENVIRONMENT = "production" }
routes = [
  { pattern = "gastronomos.clubemkt.digital/*", zone_name = "clubemkt.digital" }
]